import { Platform, StyleSheet } from 'react-native';
import {
  COLORS,
  FONT_SIZE,
  FONTS,
  RADIUS,
  SCREEN_HEIGHT,
  SIZES,
  SPACING,
} from '../../../constants';

const styles = StyleSheet.create({
  container: { width: '100%', marginVertical: SPACING.sm },
  trigger: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    padding: SPACING.xs,
    borderRadius: RADIUS.lg,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    // height: 60,
  },
  iconCircle: {
    width: 34,
    height: 34,
    borderRadius: RADIUS.round,
    backgroundColor: COLORS.goldLightBg,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: SPACING.md,
  },
  triggerText: {
    fontSize: FONT_SIZE.sm,
    color: COLORS.textPrimary,
    fontFamily: FONTS.semiBold,
  },
  placeholder: { color: COLORS.textSecondary, fontFamily: FONTS.regular },

  // Modal Content
  modalContainer: { flex: 1, backgroundColor: COLORS.grey50 },
  fullMap: { flex: 1 },
  searchHeader: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    paddingHorizontal: SPACING.lg,
    zIndex: 100,
  },
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.md,
    height: 56,
    paddingHorizontal: SPACING.md,
    marginTop: Platform.OS === 'android' ? 40 : SPACING.xs + 6,
    elevation: 6,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
  },
  searchBoxActive: {
    borderRadius: 0,
    marginTop: 0,
    marginHorizontal: -SPACING.lg,
    elevation: 0,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  searchIconBtn: { marginRight: 10, padding: SPACING.xs },
  searchInput: {
    flex: 1,
    fontSize: FONT_SIZE.md,
    color: COLORS.textPrimary,
    fontFamily: FONTS.medium,
  },

  resultsPanel: {
    backgroundColor: COLORS.white,
    height: SCREEN_HEIGHT,
    marginHorizontal: -SPACING.lg,
  },
  resultItem: {
    flexDirection: 'row',
    padding: SPACING.lg,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    alignItems: 'center',
  },
  resultIcon: {
    width: SIZES.avatarMd,
    height: SIZES.avatarMd,
    borderRadius: RADIUS.xl,
    backgroundColor: COLORS.grey50,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: SPACING.md,
  },
  resultMain: {
    fontSize: FONT_SIZE.md,
    fontFamily: FONTS.semiBold,
    color: COLORS.textPrimary,
  },
  resultSub: {
    fontSize: FONT_SIZE.sm,
    fontFamily: FONTS.regular,
    color: COLORS.textSecondary,
    marginTop: SPACING.xxs,
  },
  emptyState: { padding: SPACING.giant, alignItems: 'center' },
  emptyText: {
    color: COLORS.textSecondary,
    fontSize: FONT_SIZE.lg,
    fontFamily: FONTS.regular,
  },

  // Marker
  markerFixed: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    marginLeft: -50,
    marginTop: -60,
    width: 100,
    alignItems: 'center',
    zIndex: 1,
  },
  pinBubble: {
    backgroundColor: COLORS.textPrimary,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: RADIUS.md,
    marginBottom: 2,
  },
  pinBubbleText: {
    color: COLORS.white,
    fontSize: FONT_SIZE.xs,
    fontFamily: FONTS.bold,
    textTransform: 'uppercase',
  },
  markerShadow: {
    width: 12,
    height: 6,
    backgroundColor: COLORS.black,
    borderRadius: RADIUS.sm,
    marginTop: -4,
  },

  // Bottom Elements
  fabLocation: {
    position: 'absolute',
    bottom: 220,
    right: SPACING.xl,
    backgroundColor: COLORS.white,
    width: 52,
    height: 52,
    borderRadius: RADIUS.round,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
    shadowColor: COLORS.black,
    shadowOpacity: 0.2,
    shadowRadius: 10,
  },
  bottomSheet: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: COLORS.white,
    padding: SPACING.xxl,
    borderTopLeftRadius: RADIUS.xl + 4,
    borderTopRightRadius: RADIUS.xl + 4,
    elevation: 25,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: -10 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
  },
  addressContainer: { flexDirection: 'row', marginBottom: SPACING.xxl },
  addressIndicator: {
    marginRight: SPACING.lg,
    alignItems: 'center',
    paddingTop: 6,
  },
  dotOuter: {
    width: 14,
    height: 14,
    borderRadius: RADIUS.round,
    backgroundColor: COLORS.goldLightBg,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dotInner: {
    width: 6,
    height: 6,
    borderRadius: RADIUS.round,
    backgroundColor: COLORS.primary,
  },
  line: {
    flex: 1,
    width: 2,
    backgroundColor: COLORS.border,
    marginTop: SPACING.xs,
  },
  label: {
    fontSize: FONT_SIZE.sm,
    fontFamily: FONTS.bold,
    color: COLORS.textSecondary,
    letterSpacing: 1.5,
  },
  addressText: {
    fontSize: FONT_SIZE.md,
    fontFamily: FONTS.medium,
    color: COLORS.textPrimary,
    marginTop: 6,
    lineHeight: 22,
  },
  skeletonLine: {
    height: 20,
    width: '100%',
    backgroundColor: COLORS.grey50,
    borderRadius: RADIUS.xs,
    marginTop: 10,
  },
  confirmButton: {
    backgroundColor: COLORS.primary,
    height: 58,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  confirmButtonText: {
    color: COLORS.white,
    fontSize: FONT_SIZE.sm,
    fontFamily: FONTS.bold,
  },
});

export default styles;
