import { StyleSheet } from 'react-native';
import {
  COLORS,
  FONT_SIZE,
  FONTS,
  ICON_SIZE,
  RADIUS,
  SIZES,
  SPACING,
} from '../../../constants';

const styles = StyleSheet.create({
  cardContainer: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    borderWidth: 1,
    borderColor: COLORS.grey200,
    marginBottom: SPACING.sm,
    elevation: 2,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
  },

  topSection: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: SPACING.sm,
  },
  avatarWrapper: {
    marginRight: SPACING.sm,
  },
  avatarImage: {
    width: SIZES.avatar54,
    height: SIZES.avatar54,
    borderRadius: RADIUS.round,
    borderWidth: 1.5,
    borderColor: COLORS.goldBorder,
  },
  avatarPlaceholder: {
    width: SIZES.avatar54,
    height: SIZES.avatar54,
    borderRadius: RADIUS.round,
    backgroundColor: COLORS.goldLightBg,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: COLORS.goldBorder,
  },
  avatarPlaceholderIcon: {
    width: ICON_SIZE.lg,
    height: ICON_SIZE.lg,
    tintColor: COLORS.primary,
  },

  infoWrapper: {
    flex: 1,
    justifyContent: 'center',
  },
  registeredNameText: {
    fontSize: FONT_SIZE.md,
    fontFamily: FONTS.bold,
    color: COLORS.textPrimary,
    lineHeight: 20,
  },
  barnNameText: {
    fontSize: FONT_SIZE.xs,
    fontFamily: FONTS.medium,
    color: COLORS.textSecondary,
    marginTop: 2,
  },
  breedTag: {
    alignSelf: 'flex-start',
    backgroundColor: COLORS.goldLightBg,
    paddingHorizontal: SPACING.xs,
    paddingVertical: 2,
    borderRadius: RADIUS.xs,
    marginTop: 4,
    borderWidth: 1,
    borderColor: COLORS.goldBorder,
  },
  breedTagText: {
    fontSize: FONT_SIZE.mini,
    fontFamily: FONTS.semiBold,
    color: COLORS.primary,
  },

  actionsWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
    marginLeft: SPACING.xs,
  },
  editActionBtn: {
    width: SIZES.avatarSm,
    height: SIZES.avatarSm,
    borderRadius: RADIUS.round,
    backgroundColor: COLORS.goldLightBg,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: SIZES.borderWidthThin,
    borderColor: COLORS.goldBorder,
  },
  deleteActionBtn: {
    width: SIZES.avatarSm,
    height: SIZES.avatarSm,
    borderRadius: RADIUS.round,
    backgroundColor: COLORS.redLightBg,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: SIZES.borderWidthThin,
    borderColor: COLORS.redBorder,
  },

  pillsRow: {
    flexDirection: 'row',
    backgroundColor: COLORS.slate50,
    borderRadius: RADIUS.sm,
    paddingVertical: SPACING.xs,
    paddingHorizontal: SPACING.xs,
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: SPACING.xs,
    borderWidth: 1,
    borderColor: COLORS.divider,
  },
  pillItem: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: 2,
  },
  pillLabel: {
    fontSize: FONT_SIZE.xxs,
    fontFamily: FONTS.medium,
    color: COLORS.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  pillValue: {
    fontSize: FONT_SIZE.xs,
    fontFamily: FONTS.bold,
    color: COLORS.textPrimary,
    marginTop: 1,
  },

  docsBadgesRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.xs,
    marginTop: SPACING.xs / 2,
  },
  docBadgeSuccess: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: COLORS.emeraldLightBg,
    paddingHorizontal: SPACING.xs,
    paddingVertical: 3,
    borderRadius: RADIUS.xs,
    borderWidth: 1,
    borderColor: COLORS.emeraldBorder,
  },
  docBadgeTextSuccess: {
    fontSize: FONT_SIZE.mini,
    fontFamily: FONTS.semiBold,
    color: COLORS.emeraldDark,
  },

  notesBox: {
    flexDirection: 'row',
    backgroundColor: COLORS.goldLightBg,
    borderRadius: RADIUS.sm,
    padding: SPACING.xs + 2,
    marginTop: SPACING.xs,
    borderWidth: 1,
    borderColor: COLORS.goldBorder,
  },
  fileicon: { marginTop: 2 },
  notesContent: {
    marginLeft: SPACING.xs,
    flex: 1,
  },
  notesHeading: {
    fontSize: FONT_SIZE.mini,
    fontFamily: FONTS.bold,
    color: COLORS.primary,
    textTransform: 'uppercase',
  },
  notesBody: {
    fontSize: FONT_SIZE.xs,
    fontFamily: FONTS.medium,
    color: COLORS.textSecondary,
    lineHeight: 16,
    marginTop: 1,
  },
});

export default styles