
import { StyleSheet } from 'react-native';
import { COLORS, FONTS, RADIUS, SPACING, FONT_SIZE } from '../../../../../constants';

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: COLORS.white },
    scrollView: { flex: 1 },
    scrollContent: { padding: SPACING.lg, paddingBottom: SPACING.massive },
    titleRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: SPACING.xl,
    },
    mainTitle: {
        fontSize: FONT_SIZE.title,
        fontFamily: FONTS.bold,
        color: COLORS.textPrimary,
    },
    cancelText: { color: COLORS.primary, fontFamily: FONTS.medium },
    noHorsesAlert: {
        flexDirection: 'row',
        backgroundColor: COLORS.goldLightBg,
        padding: SPACING.md,
        borderRadius: RADIUS.md,
        alignItems: 'center',
        marginBottom: SPACING.md,
        gap: 10,
    },
    noHorsesText: {
        flex: 1,
        fontSize: FONT_SIZE.md,
        color: COLORS.primary,
        fontFamily: FONTS.medium,
    },
    horseSection: {
        marginBottom: SPACING.xl,
        backgroundColor: '#FBFAf8',
        padding: SPACING.md,
        borderRadius: RADIUS.md,
        borderWidth: 1,
        borderColor: COLORS.divider,
    },
    dividerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: SPACING.md,
    },
    line: { flex: 1, height: 1, backgroundColor: COLORS.grey300 },
    sectionLabel: {
        fontSize: FONT_SIZE.md,
        fontFamily: FONTS.bold,
        color: COLORS.grey500,
        marginHorizontal: 10,
    },
    row: { flexDirection: 'row', justifyContent: 'space-between' },
    radioLabel: {
        fontSize: FONT_SIZE.lg,
        fontFamily: FONTS.semiBold,
        color: COLORS.grey700,
        marginTop: SPACING.md,
        marginBottom: SPACING.sm,
    },
    radioGroup: { flexDirection: 'row', gap: 30, marginBottom: SPACING.md },
    radioButton: { flexDirection: 'row', alignItems: 'center' },
    radioOuter: {
        height: 20,
        width: 20,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: COLORS.grey300,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 10,
    },
    radioOuterActive: { borderColor: COLORS.primary },
    radioInner: {
        height: 10,
        width: 10,
        borderRadius: 5,
        backgroundColor: COLORS.primary,
    },
    radioText: {
        fontSize: FONT_SIZE.lg,
        color: COLORS.textPrimary,
        fontFamily: FONTS.medium,
    },
    footer: {
        flexDirection: 'row',
        paddingVertical: SPACING.lg,
        gap: SPACING.md,
        marginTop: SPACING.xl,
    },
    prevButton: {
        flex: 1,
        height: 52,
        borderRadius: RADIUS.md,
        borderWidth: 1,
        borderColor: COLORS.divider,
        justifyContent: 'center',
        alignItems: 'center',
    },
    prevButtonText: { fontFamily: FONTS.bold, color: COLORS.grey600 },
    nextButton: {
        flex: 1,
        height: 52,
        borderRadius: RADIUS.md,
        backgroundColor: COLORS.primary,
        justifyContent: 'center',
        alignItems: 'center',
    },
    disabledButton: { backgroundColor: COLORS.grey300 },
    nextButtonText: { fontFamily: FONTS.bold, color: COLORS.white },
});
export default styles