import { StyleSheet } from 'react-native';
import { COLORS, FONTS, FONT_SIZE, SPACING } from '../../../../constants';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F3F7FA', // Modern crisp light blue-grey background matching screenshot
  },
  headerBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    backgroundColor: '#F3F7FA',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.lg,
    color: COLORS.slate900,
  },
  brandBadge: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.white,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: COLORS.grey200,
  },
  scrollContent: {
    paddingHorizontal: SPACING.md,
    paddingBottom: 40,
  },

  // Sub Header Chips Row
  subHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginVertical: 12,
  },
  tripIdBadge: {
    backgroundColor: '#E0EDF8',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  tripIdText: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.xs,
    color: '#2C5282',
    letterSpacing: 0.5,
  },
  statusBadgeCompleted: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#DCFCE7',
    borderWidth: 1,
    borderColor: '#86EFAC',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 5,
    gap: 5,
  },
  statusDotGreen: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#15803D',
  },
  statusTextCompleted: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.xs,
    color: '#15803D',
    letterSpacing: 0.5,
  },
  priceText: {
    fontFamily: FONTS.bold,
    fontSize: 18,
    color: COLORS.slate900,
  },

  // Map Telemetry Card
  mapCard: {
    backgroundColor: COLORS.slate900,
    borderRadius: 20,
    overflow: 'hidden',
    marginBottom: 16,
    height: 220,
    position: 'relative',
  },
  mapView: {
    ...StyleSheet.absoluteFillObject,
  },
  markerCircleGreen: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#10B981',
    borderWidth: 2,
    borderColor: COLORS.white,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3,
    elevation: 4,
  },
  markerCircleRed: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#EF4444',
    borderWidth: 2,
    borderColor: COLORS.white,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3,
    elevation: 4,
  },
  markerCircleBlue: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#2563EB',
    borderWidth: 2,
    borderColor: COLORS.white,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3,
    elevation: 4,
  },

  mapBgPlaceholder: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#2A4365', // Dark map navy
  },
  mapSimulatedGrid: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.15,
  },
  mapHeaderOverlay: {
    position: 'absolute',
    top: 12,
    left: 12,
    right: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 2,
  },
  haulerBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.92)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    gap: 6,
  },
  haulerText: {
    fontFamily: FONTS.bold,
    fontSize: 11,
    color: COLORS.slate900,
  },
  compassBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.92)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  telemetryPingBox: {
    position: 'absolute',
    bottom: 12,
    left: 12,
    right: 12,
    backgroundColor: COLORS.white,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  pingLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  pingIconCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#EBF8FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pingLabel: {
    fontFamily: FONTS.bold,
    fontSize: 9,
    color: COLORS.slate500,
    letterSpacing: 0.5,
  },
  pingCoords: {
    fontFamily: FONTS.bold,
    fontSize: 12,
    color: COLORS.slate900,
  },
  pingRight: {
    alignItems: 'flex-end',
  },
  pingVerifiedTag: {
    fontFamily: FONTS.bold,
    fontSize: 10,
    color: '#92400E',
  },
  pingDate: {
    fontFamily: FONTS.medium,
    fontSize: 11,
    color: COLORS.slate600,
  },

  // Location Card
  card: {
    backgroundColor: COLORS.white,
    borderRadius: 20,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 6,
    elevation: 2,
  },
  locationTimelineRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    marginBottom: 14,
  },
  timelineGraphic: {
    width: 24,
    alignItems: 'center',
    marginRight: 10,
    paddingVertical: 4,
  },
  dotOrigin: {
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 2.5,
    borderColor: '#1E293B',
    backgroundColor: '#10B981',
  },
  timelineLine: {
    flex: 1,
    width: 2,
    backgroundColor: '#CBD5E1',
    marginVertical: 4,
  },
  dotDestination: {
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 2.5,
    borderColor: '#1E293B',
    backgroundColor: '#D97706',
  },
  locationDetailsCol: {
    flex: 1,
    justifyContent: 'space-between',
  },
  locationBlock: {
    marginVertical: 2,
  },
  locationHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  locationTitle: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.md,
    color: COLORS.slate900,
  },
  locationTag: {
    fontFamily: FONTS.bold,
    fontSize: 11,
    color: COLORS.slate500,
  },
  locationTagDelivered: {
    fontFamily: FONTS.bold,
    fontSize: 11,
    color: '#92400E',
  },
  locationSubtext: {
    fontFamily: FONTS.medium,
    fontSize: FONT_SIZE.xs,
    color: COLORS.slate500,
    marginTop: 1,
  },
  tripSummaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F0F7FF',
    borderRadius: 12,
    padding: 12,
    marginTop: 4,
  },
  summaryCol: {
    alignItems: 'center',
  },
  summaryLabel: {
    fontFamily: FONTS.bold,
    fontSize: 10,
    color: COLORS.slate500,
    marginBottom: 2,
  },
  summaryValue: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.slate900,
  },

  // Card Section Header
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  cardTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  cardTitle: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.md,
    color: COLORS.slate900,
  },
  badgeTagAmber: {
    backgroundColor: '#FEF3C7',
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  badgeTagAmberText: {
    fontFamily: FONTS.bold,
    fontSize: 10,
    color: '#B45309',
  },

  // Horse Details
  horseCardInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
  },
  horseImage: {
    width: 72,
    height: 72,
    borderRadius: 14,
    backgroundColor: '#F1F5F9',
  },
  horseImageFallback: {
    width: 72,
    height: 72,
    borderRadius: 14,
    backgroundColor: COLORS.goldCreamBg,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: COLORS.goldBorder,
  },
  horseMainInfo: {
    flex: 1,
  },
  horseTitle: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.md,
    color: COLORS.slate900,
  },
  horseSubtitle: {
    fontFamily: FONTS.medium,
    fontSize: FONT_SIZE.xs,
    color: COLORS.slate600,
    marginBottom: 6,
  },
  pillRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  characteristicPill: {
    backgroundColor: '#E0F2FE',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  characteristicText: {
    fontFamily: FONTS.bold,
    fontSize: 10,
    color: '#0369A1',
  },
  careNoteBox: {
    backgroundColor: '#EFF6FF',
    borderRadius: 10,
    padding: 10,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#BFDBFE',
  },
  careNoteHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
  },
  careNoteTitle: {
    fontFamily: FONTS.bold,
    fontSize: 11,
    color: '#1E40AF',
  },
  careNoteText: {
    fontFamily: FONTS.italic,
    fontSize: FONT_SIZE.xs,
    color: '#1E3A8A',
  },
  signOffRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    padding: 10,
    gap: 10,
  },
  avatarCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#064E3B',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarInitials: {
    fontFamily: FONTS.bold,
    fontSize: 12,
    color: COLORS.white,
  },
  signOffInfo: {
    flex: 1,
  },
  signOffName: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.slate900,
  },
  signOffSub: {
    fontFamily: FONTS.regular,
    fontSize: 11,
    color: COLORS.slate500,
  },

  // Rig Telematics
  telematicsGrid: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 12,
  },
  metricCard: {
    flex: 1,
    backgroundColor: '#F0FDF4',
    borderWidth: 1,
    borderColor: '#DCFCE7',
    borderRadius: 12,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  metricLabel: {
    fontFamily: FONTS.bold,
    fontSize: 9,
    color: '#15803D',
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  metricValue: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.md,
    color: COLORS.slate900,
  },
  capacityRow: {
    backgroundColor: '#F8FAFC',
    borderRadius: 10,
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  capacityText: {
    fontFamily: FONTS.medium,
    fontSize: FONT_SIZE.xs,
    color: COLORS.slate700,
  },
  capacityValue: {
    fontFamily: FONTS.bold,
    color: COLORS.slate900,
  },

  // Passport Section
  badgeTagGreen: {
    backgroundColor: '#DCFCE7',
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  badgeTagGreenText: {
    fontFamily: FONTS.bold,
    fontSize: 10,
    color: '#15803D',
  },
  docRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F0F9FF',
    borderRadius: 12,
    padding: 10,
    marginBottom: 8,
    gap: 10,
  },
  docIconTile: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: COLORS.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  docInfo: {
    flex: 1,
  },
  docTitle: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.slate900,
  },
  docSubtext: {
    fontFamily: FONTS.medium,
    fontSize: 11,
    color: COLORS.slate500,
    marginTop: 1,
  },
  downloadBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
});

export default styles;
