import { StyleSheet } from "react-native";
import { COLORS, FONTS } from "../../../../constants";

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  screenWrapper: {
    flex: 1,
  },
  container: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 40,
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.background,
  },
  card: {
    backgroundColor: COLORS.white,
    borderWidth: 1.5,
    borderColor: COLORS.goldBorder,
    borderRadius: 8,
    marginBottom: 20,
    overflow: 'hidden',
  },
  cardHeader: {
    backgroundColor: COLORS.goldLightBg,
    borderBottomWidth: 1.5,
    borderColor: COLORS.goldBorder,
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  accordionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: COLORS.goldLightBg,
    borderBottomWidth: 1.5,
    borderColor: COLORS.goldBorder,
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  cardHeaderTitle: {
    fontFamily: FONTS.bold,
    fontSize: 15,
    color: COLORS.goldDarkText,
  },
  cardBody: {
    padding: 16,
  },
  routeHeaderBox: {
    backgroundColor: COLORS.goldLightBg,
    borderWidth: 1.2,
    borderColor: COLORS.goldBorder,
    borderRadius: 8,
    padding: 16,
    alignItems: 'center',
    marginBottom: 16,
  },
  routeLabel: {
    fontFamily: FONTS.bold,
    fontSize: 10,
    color: COLORS.goldPrimary,
    letterSpacing: 1,
    marginBottom: 6,
  },
  routePlaces: {
    fontFamily: FONTS.bold,
    fontSize: 18,
    color: COLORS.textPrimary,
    marginBottom: 12,
  },
  horseCountBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.goldBorder,
    backgroundColor: COLORS.white,
    borderRadius: 6,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  badgeIcon: {
    marginRight: 6,
  },
  horseCountText: {
    fontFamily: FONTS.bold,
    fontSize: 12,
    color: COLORS.goldDarkText,
  },
  tripStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1.2,
    borderColor: COLORS.goldBorder,
    borderRadius: 6,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  tripStatusLabel: {
    fontFamily: FONTS.bold,
    fontSize: 13,
    color: COLORS.textLight,
  },
  statusIndicatorRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  greenActiveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.greenActive,
    marginRight: 6,
  },
  greenActiveText: {
    fontFamily: FONTS.bold,
    fontSize: 12,
    color: COLORS.greenActive,
  },
  stopCard: {
    flexDirection: 'row',
    backgroundColor: COLORS.goldLightBg,
    borderWidth: 1.2,
    borderColor: COLORS.goldBorder,
    borderRadius: 8,
    padding: 16,
    alignItems: 'center',
  },
  stopIconContainer: {
    width: 36,
    height: 36,
    borderRadius: 6,
    backgroundColor: COLORS.goldPrimary,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  stopDetails: {
    flex: 1,
  },
  stopLabel: {
    fontFamily: FONTS.bold,
    fontSize: 10,
    color: COLORS.goldPrimary,
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  stopLocation: {
    fontFamily: FONTS.bold,
    fontSize: 14,
    color: COLORS.textPrimary,
    marginBottom: 4,
  },
  stopMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  stopMetaText: {
    fontFamily: FONTS.regular,
    fontSize: 11,
    color: COLORS.textLight,
    marginLeft: 4,
  },
  metaSpacing: {
    marginLeft: 12,
  },
  connectorWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
    height: 32,
    position: 'relative',
  },
  dashedLine: {
    width: 1,
    height: 10,
    borderWidth: 1,
    borderColor: COLORS.goldBorder,
    borderStyle: 'dashed',
  },
  dashedCenterDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    borderWidth: 1.5,
    borderColor: COLORS.goldPrimary,
    backgroundColor: COLORS.goldLightBg,
    marginVertical: 2,
  },
  horseDetailsWrapper: {
    borderWidth: 1.2,
    borderColor: COLORS.goldBorder,
    borderRadius: 8,
    overflow: 'hidden',
    marginBottom: 16,
  },
  horseImage: {
    width: '100%',
    height: 140,
    resizeMode: "stretch",
  },
  horseImageFallback: {
    width: '100%',
    height: 140,
    backgroundColor: COLORS.grey200,
  },
  horseGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    padding: 12,
  },
  gridCell: {
    width: '50%',
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  gridLabel: {
    fontFamily: FONTS.bold,
    fontSize: 9,
    color: COLORS.textLight,
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  gridValue: {
    fontFamily: FONTS.bold,
    fontSize: 14,
    color: COLORS.textPrimary,
  },
  notesBox: {
    backgroundColor: COLORS.goldLightBg,
    borderWidth: 1.2,
    borderColor: COLORS.goldBorder,
    borderRadius: 8,
    padding: 14,
    marginBottom: 16,
  },
  notesBoxLabel: {
    fontFamily: FONTS.bold,
    fontSize: 10,
    color: COLORS.goldPrimary,
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  notesBoxText: {
    fontFamily: FONTS.regular,
    fontSize: 13,
    color: COLORS.textSecondary,
    lineHeight: 18,
  },
  goldButton: {
    flexDirection: 'row',
    backgroundColor: COLORS.goldPrimary,
    height: 48,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnIcon: {
    marginRight: 8,
  },
  goldButtonText: {
    fontFamily: FONTS.bold,
    fontSize: 15,
    color: COLORS.white,
  },
  emptyCard: {
    backgroundColor: COLORS.white,
    borderWidth: 1.5,
    borderColor: COLORS.goldBorder,
    borderRadius: 8,
    padding: 24,
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 20,
  },
  emptyText: {
    fontFamily: FONTS.regular,
    fontSize: 14,
    color: COLORS.textSecondary,
    textAlign: 'center',
    marginBottom: 16,
  },
  refreshBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.goldPrimary,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
  },
  refreshBtnText: {
    fontFamily: FONTS.bold,
    fontSize: 13,
    color: COLORS.white,
    marginLeft: 8,
  },
  vehicleImageContainer: {
    width: '100%',
    height: 180,
    borderRadius: 8,
    overflow: 'hidden',
    position: 'relative',
    marginBottom: 16,
  },
  vehicleImage: {
    width: '100%',
    height: '100%',
    resizeMode: "contain",
  },
  vehicleImageFallback: {
    width: '100%',
    height: '100%',
    backgroundColor: COLORS.grey200,
  },
  tagBadge: {
    position: 'absolute',
    left: 12,
    top: 12,
    backgroundColor: COLORS.white,
    borderRadius: 4,
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  tagBadgeText: {
    fontFamily: FONTS.bold,
    fontSize: 10,
    color: COLORS.goldDarkText,
  },
  vehicleMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  flexOne: {
    flex: 1,
  },
  vehicleNum: {
    fontFamily: FONTS.bold,
    fontSize: 20,
    color: COLORS.textPrimary,
  },
  vehicleSubDetails: {
    fontFamily: FONTS.regular,
    fontSize: 13,
    color: COLORS.textSecondary,
    marginTop: 2,
  },
  readyBadge: {
    borderWidth: 1.2,
    borderColor: COLORS.goldBorder,
    borderRadius: 4,
    backgroundColor: COLORS.goldLightBg,
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  readyBadgeText: {
    fontFamily: FONTS.bold,
    fontSize: 11,
    color: COLORS.goldPrimary,
  },
  vehicleGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 16,
    gap: 8,
  },
  vehicleGridCell: {
    width: '48%', // Sits neatly in a 2x2 grid
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.grey50,
    borderRadius: 6,
    padding: 12,
  },
  vLabel: {
    fontFamily: FONTS.bold,
    fontSize: 9,
    color: COLORS.textLight,
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  vValue: {
    fontFamily: FONTS.bold,
    fontSize: 13,
    color: COLORS.textPrimary,
  },
});

export default styles