import { StyleSheet } from "react-native";
import { COLORS, FONT_SIZE, FONTS, RADIUS, SPACING } from "../../../../constants";

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.background },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.divider,
  },
  backBtn: { padding: 4 },
  headerTitle: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.lg,
    color: COLORS.textPrimary,
  },
  content: { padding: SPACING.lg },
  heroCard: { alignItems: 'center', marginBottom: SPACING.lg },
  successCircle: { marginBottom: SPACING.sm },
  heroStatus: {
    fontSize: FONT_SIZE.xs,
    fontFamily: FONTS.bold,
    color: COLORS.success,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  heroAmount: {
    fontSize: FONT_SIZE.heading,
    fontFamily: FONTS.bold,
    color: COLORS.textPrimary,
    marginVertical: 2,
  },
  heroDate: { fontSize: FONT_SIZE.xs, color: COLORS.textSecondary },
  infoCard: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    marginBottom: SPACING.md,
    borderWidth: 1,
    borderColor: COLORS.divider,
  },
  idRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  label: {
    fontSize: FONT_SIZE.xs,
    fontFamily: FONTS.bold,
    color: COLORS.textLight,
    letterSpacing: 1,
  },
  idText: {
    fontSize: FONT_SIZE.sm,
    fontFamily: FONTS.medium,
    color: COLORS.textPrimary,
    marginTop: 2,
  },
  copyBtn: {
    padding: 8,
    backgroundColor: COLORS.goldLightBg,
    borderRadius: RADIUS.sm,
  },
  sectionTitle: {
    fontSize: FONT_SIZE.xs,
    fontFamily: FONTS.bold,
    color: COLORS.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: SPACING.xs,
    marginLeft: 4,
  },
  shipperRow: { flexDirection: 'row', alignItems: 'center', gap: SPACING.md },
  avatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: COLORS.grey100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shipperName: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.sm,
    color: COLORS.textPrimary,
  },
  shipperEmail: { fontSize: FONT_SIZE.xs, color: COLORS.textSecondary },
  phoneBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  routeRow: { flexDirection: 'row', alignItems: 'center', gap: SPACING.md },
  routeText: {
    flex: 1,
    fontSize: FONT_SIZE.sm,
    fontFamily: FONTS.medium,
    color: COLORS.textPrimary,
  },
  routeLine: {
    width: 2,
    height: 16,
    backgroundColor: COLORS.goldBorder,
    marginLeft: 8,
    marginVertical: 2,
  },
  receiptBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    padding: SPACING.md,
    backgroundColor: COLORS.goldLightBg,
    borderRadius: RADIUS.md,
    borderStyle: 'dashed',
    borderWidth: 1,
    borderColor: COLORS.primary,
  },
  receiptBtnText: {
    fontFamily: FONTS.bold,
    color: COLORS.primary,
    fontSize: FONT_SIZE.sm,
  },
});

export default styles;