import { StyleSheet } from 'react-native';
import { COLORS, FONT_SIZE, FONTS, SPACING } from '../../../../../constants';

const styles = StyleSheet.create({
  card: {
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.grey200,
    borderRadius: 20,
    marginBottom: SPACING.md,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  accordionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderColor: COLORS.grey200,
    paddingVertical: 14,
    paddingHorizontal: 18,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  headerLeftRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  cardHeaderTitle: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.md,
    color: COLORS.slate900,
  },
  cardBody: {
    padding: 16,
  },
  vehicleImageContainer: {
    width: '100%',
    aspectRatio: 16 / 9,
    borderRadius: 16,
    overflow: 'hidden',
    position: 'relative',
    marginBottom: 16,
    backgroundColor: COLORS.slate100,
  },
  vehicleImage: {
    width: '100%',
    height: '100%',
  },
  vehicleImageFallback: {
    width: '100%',
    height: '100%',
    backgroundColor: COLORS.goldCreamBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tagBadge: {
    position: 'absolute',
    left: 12,
    top: 12,
    backgroundColor: COLORS.slateOverlay85,
    borderRadius: 8,
    paddingVertical: 4,
    paddingHorizontal: 10,
  },
  tagBadgeText: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.goldLightText,
    letterSpacing: 0.5,
  },
  vehicleMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  flexOne: {
    flex: 1,
  },
  vehicleNum: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.lg,
    color: COLORS.slate900,
  },
  vehicleSubDetails: {
    fontFamily: FONTS.regular,
    fontSize: FONT_SIZE.xs,
    color: COLORS.slate500,
    marginTop: 2,
  },
  readyBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderWidth: 1,
    borderColor: COLORS.greenBorder,
    borderRadius: 20,
    backgroundColor: COLORS.greenLightBg,
    paddingVertical: 5,
    paddingHorizontal: 12,
  },
  readyBadgeText: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.greenSuccess,
    letterSpacing: 0.5,
  },
  vehicleGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 16,
    gap: 10,
  },
  vehicleGridCell: {
    width: '48%',
    borderWidth: 1,
    borderColor: COLORS.grey200,
    backgroundColor: COLORS.slate50,
    borderRadius: 14,
    padding: 12,
  },
  vLabel: {
    fontFamily: FONTS.bold,
    fontSize: 10,
    color: COLORS.slate400,
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  vValue: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.sm,
    color: COLORS.slate900,
  },
  notesBox: {
    backgroundColor: COLORS.goldCreamBg,
    borderWidth: 1,
    borderColor: COLORS.goldBorder,
    borderRadius: 14,
    padding: 14,
  },
  notesHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 6,
  },
  notesBoxLabel: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.primary,
    letterSpacing: 0.5,
  },
  notesBoxText: {
    fontFamily: FONTS.regular,
    fontSize: FONT_SIZE.xs,
    color: COLORS.goldDarkText,
    lineHeight: 18,
  },
});

export default styles;
