import { StyleSheet } from 'react-native';
import {
  COLORS,
  FONT_SIZE,
  FONTS,
  RADIUS,
  SPACING,
} from '../../../../../constants';

const styles = StyleSheet.create({
  card: {
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.goldBorder,
    borderRadius: RADIUS.md,
    marginBottom: SPACING.md,
    overflow: 'hidden',
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: COLORS.goldLightBg,
    borderBottomWidth: 1,
    borderColor: COLORS.goldBorder,
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  headerLeftRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  cardHeaderTitle: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.md,
    color: COLORS.goldDarkText,
  },
  statusBadgePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: RADIUS.round,
  },
  transitPill: {
    backgroundColor: COLORS.greenBadgeBg,
    borderWidth: 1,
    borderColor: COLORS.greenBadgeBorder,
  },
  pendingPill: {
    backgroundColor: COLORS.brandBrownLightBg,
    borderWidth: 1,
    borderColor: COLORS.goldBorder,
  },
  statusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  greenDot: { backgroundColor: COLORS.greenSuccessDark },
  amberDot: { backgroundColor: COLORS.amberPrimary },
  statusPillText: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.xs,
    letterSpacing: 0.5,
  },
  greenPillText: { color: COLORS.greenBadgeText },
  amberPillText: { color: COLORS.amberWarning },
  cardBody: {
    padding: 16,
  },
  routeHeaderBox: {
    backgroundColor: COLORS.goldLightBg,
    borderWidth: 1,
    borderColor: COLORS.goldBorder,
    borderRadius: RADIUS.sm,
    padding: 16,
    alignItems: 'center',
    marginBottom: 16,
  },
  routeLabel: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.primary,
    letterSpacing: 1.2,
    marginBottom: 4,
  },
  routePlaces: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.md,
    color: COLORS.textPrimary,
    marginBottom: 10,
  },
  metricsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  metricChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.goldBorder,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: RADIUS.xs,
  },
  metricChipText: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.goldDarkText,
  },
  timelineContainer: {
    marginVertical: 4,
  },
  stopCard: {
    flexDirection: 'row',
    backgroundColor: COLORS.grey50,
    borderWidth: 1,
    borderColor: COLORS.divider,
    borderRadius: RADIUS.sm,
    padding: 12,
    alignItems: 'center',
  },
  nodeIconCircle: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  stopDetails: {
    flex: 1,
  },
  stopLabel: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.mini,
    color: COLORS.textSecondary,
    letterSpacing: 0.6,
    marginBottom: 2,
  },
  stopLocation: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.sm,
    color: COLORS.textPrimary,
    marginBottom: 4,
    lineHeight: 18,
  },
  stopMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  stopMetaText: {
    fontFamily: FONTS.medium,
    fontSize: FONT_SIZE.xs,
    color: COLORS.textSecondary,
  },
  connectorWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
    height: 20,
    marginVertical: 2,
  },
  verticalTrackLine: {
    width: 2,
    height: '100%',
    backgroundColor: COLORS.goldBorder,
  },
});

export default styles;
