import { StyleSheet, Platform } from 'react-native';
import { COLORS, FONTS, FONT_SIZE, SPACING } from '../../../../constants';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.background,
  },
  container: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: SPACING.lg,
    paddingTop: SPACING.md,
    paddingBottom: Platform.OS === 'ios' ? 100 : 90,
  },
  mainCard: {
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.grey200,
    borderRadius: 24,
    paddingVertical: SPACING.lg,
    paddingHorizontal: SPACING.lg,
    alignItems: 'center',
    marginBottom: SPACING.lg,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 3,
  },
  avatarWrapper: {
    width: 80,
    height: 80,
    borderWidth: 2.5,
    borderColor: COLORS.primary,
    borderRadius: 22,
    backgroundColor: COLORS.goldCreamBg,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: SPACING.sm2,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  avatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 18,
  },
  monogramBox: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  monogramText: {
    fontFamily: FONTS.bold,
    fontSize: 28,
    color: COLORS.primary,
  },
  driverName: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.lg,
    color: COLORS.slate900,
    textAlign: 'center',
    marginBottom: SPACING.xs2,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.goldBorder,
    backgroundColor: COLORS.goldCreamBg,
    borderRadius: 20,
    paddingVertical: 4,
    paddingHorizontal: 12,
    marginBottom: SPACING.lg,
  },
  statusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.primary,
    marginRight: 6,
  },
  statusText: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.goldDarkText,
    letterSpacing: 0.5,
  },
  statsRow: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
    gap: 12,
  },
  completedBox: {
    flex: 1,
    borderWidth: 1,
    borderColor: COLORS.goldBorder,
    backgroundColor: COLORS.goldCreamBg,
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  accountBox: {
    flex: 1,
    borderWidth: 1,
    borderColor: COLORS.greenBorder,
    backgroundColor: COLORS.greenLightBg,
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  accountBoxInactive: {
    borderColor: COLORS.border,
    backgroundColor: COLORS.grey100,
  },
  statLabel: {
    fontFamily: FONTS.bold,
    fontSize: 10,
    color: COLORS.primary,
    letterSpacing: 0.8,
    marginBottom: 2,
  },
  statValue: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.xl,
    color: COLORS.slate900,
  },
  detailsCard: {
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.grey200,
    borderRadius: 24,
    marginBottom: SPACING.lg,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  detailsHeader: {
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderColor: COLORS.grey200,
    paddingVertical: 14,
    paddingHorizontal: 18,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
  },
  detailsHeaderTitle: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.md,
    color: COLORS.slate900,
  },
  detailsBody: {
    paddingHorizontal: 18,
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.grey100,
  },
  detailIconTile: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: COLORS.goldCreamBg,
    borderWidth: 1,
    borderColor: COLORS.goldBorder,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  detailIcon: {
    marginRight: 0,
  },
  detailLabel: {
    fontFamily: FONTS.bold,
    fontSize: 10,
    color: COLORS.slate400,
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  detailValue: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.sm,
    color: COLORS.slate900,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  completedBadgeCount: {
    backgroundColor: COLORS.primary,
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 2,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: SPACING.sm,
  },
  badgeCountText: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.white,
  },
  shipmentsBody: {
    padding: 14,
    gap: 14,
  },
  emptyContainer: {
    alignItems: 'center',
    paddingVertical: SPACING.md,
  },
  emptyIconBox: {
    width: 44,
    height: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.goldBorder,
    backgroundColor: COLORS.goldCreamBg,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: SPACING.sm,
  },
  emptyText: {
    fontFamily: FONTS.medium,
    fontSize: FONT_SIZE.xs,
    color: COLORS.slate500,
    textAlign: 'center',
  },

  // Professional Completed Shipment Card Styles
  shipmentCard: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.grey200,
    padding: 14,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.grey100,
    marginBottom: 12,
  },
  cardHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  manifestTag: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.slate700,
  },
  statusChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.greenLightBg,
    borderWidth: 1,
    borderColor: COLORS.greenBorder,
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 3,
    gap: 4,
  },
  statusDotGreen: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.greenPrimary,
  },
  statusChipText: {
    fontFamily: FONTS.bold,
    fontSize: 10,
    color: COLORS.greenPrimary,
    textTransform: 'capitalize',
  },
  priceBadge: {
    backgroundColor: COLORS.blueLightBg,
    borderWidth: 1,
    borderColor: COLORS.blueBorder,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
    alignItems: 'flex-end',
  },
  priceAmountText: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.bluePrimary,
  },
  priceStatusText: {
    fontFamily: FONTS.medium,
    fontSize: 9,
    color: COLORS.slate500,
    textTransform: 'uppercase',
  },

  // Route Section
  routeContainer: {
    backgroundColor: COLORS.slate50,
    borderRadius: 12,
    padding: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: COLORS.slate200,
  },
  routeRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  routeIconBox: {
    width: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
    paddingTop: 2,
  },
  routeDotOrigin: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: COLORS.emeraldPrimary,
  },
  routeLineVertical: {
    width: 2,
    height: 16,
    backgroundColor: COLORS.slate300,
    marginVertical: 2,
  },
  routeContent: {
    flex: 1,
  },
  routeLabel: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.slate900,
  },
  routeCoords: {
    fontFamily: FONTS.regular,
    fontSize: 10,
    color: COLORS.slate500,
    marginTop: 1,
  },

  // Horse Preview Row
  horseSection: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.goldCreamBg,
    borderRadius: 12,
    padding: 10,
    borderWidth: 1,
    borderColor: COLORS.goldBorder,
    marginBottom: 10,
    gap: 10,
  },
  horseAvatar: {
    width: 42,
    height: 42,
    borderRadius: 10,
    backgroundColor: COLORS.goldLightBg,
    borderWidth: 1,
    borderColor: COLORS.primaryLight,
  },
  horseAvatarFallback: {
    width: 42,
    height: 42,
    borderRadius: 10,
    backgroundColor: COLORS.goldLightBg,
    borderWidth: 1,
    borderColor: COLORS.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  horseDetails: {
    flex: 1,
  },
  horseHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  horseName: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.slate900,
  },
  stallBadge: {
    backgroundColor: COLORS.goldPrimary,
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  stallBadgeText: {
    fontFamily: FONTS.bold,
    fontSize: 9,
    color: COLORS.white,
  },
  horseSubtext: {
    fontFamily: FONTS.medium,
    fontSize: 10,
    color: COLORS.slate600,
    marginTop: 2,
  },

  // Footer Vehicle & Notes Banner
  cardFooterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 4,
  },
  vehicleChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  vehicleText: {
    fontFamily: FONTS.semiBold,
    fontSize: 11,
    color: COLORS.slate700,
  },
  notesBanner: {
    backgroundColor: COLORS.amberLightBg,
    borderWidth: 1,
    borderColor: COLORS.amberBorder,
    borderRadius: 10,
    padding: 8,
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  notesText: {
    fontFamily: FONTS.regular,
    fontSize: 11,
    color: COLORS.goldDarkText,
    flex: 1,
  },
  logoutBtn: {
    backgroundColor: COLORS.redPrimary,
    borderRadius: 16,
    paddingVertical: 14,
  },

  logoutIcon: {
    marginRight: SPACING.sm,
  },
  logoutText: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.md,
    color: COLORS.white,
  },
  viewAllButton: {
    marginTop: 10,
    alignSelf: 'center',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: COLORS.primaryLight,
    width: '90%',
    alignItems: 'center',
    marginBottom: 20,
  },
  viewAllButtonText: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.sm,
    color: COLORS.white,
  },
});

export default styles;
