import { StyleSheet } from "react-native";
import { COLORS, FONTS } from "../../../../constants";


const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.background,
  },
  container: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 40,
  },
  mainCard: {
    backgroundColor: COLORS.white,
    borderWidth: 1.5,
    borderColor: COLORS.goldBorder,
    borderRadius: 8,
    paddingVertical: 24,
    paddingHorizontal: 16,
    alignItems: 'center',
    marginBottom: 20,
  },
  avatarWrapper: {
    width: 90,
    height: 90,
    borderWidth: 2,
    borderColor: COLORS.goldPrimary,
    borderRadius: 8,
    backgroundColor: COLORS.goldLightBg,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  avatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 6,
  },
  monogramBox: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  monogramText: {
    fontFamily: FONTS.bold,
    fontSize: 34,
    color: COLORS.goldPrimary,
  },
  driverName: {
    fontFamily: FONTS.bold,
    fontSize: 22,
    color: COLORS.textPrimary,
    textAlign: 'center',
    marginBottom: 8,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.goldBorder,
    backgroundColor: COLORS.goldLightBg,
    borderRadius: 16,
    paddingVertical: 4,
    paddingHorizontal: 14,
    marginBottom: 24,
  },
  statusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.goldPrimary,
    marginRight: 6,
  },
  statusText: {
    fontFamily: FONTS.bold,
    fontSize: 11,
    color: COLORS.goldDarkText,
    letterSpacing: 0.5,
  },
  statsRow: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
  },
  completedBox: {
    flex: 1,
    marginRight: 8,
    borderWidth: 1.5,
    borderColor: COLORS.goldBorder,
    backgroundColor: COLORS.goldLightBg,
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  accountBox: {
    flex: 1,
    marginLeft: 8,
    borderWidth: 1.5,
    borderColor: COLORS.greenBorder,
    backgroundColor: COLORS.greenLightBg,
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  accountBoxInactive: {
    borderColor: COLORS.border,
    backgroundColor: COLORS.grey100,
  },
  statLabel: {
    fontFamily: FONTS.bold,
    fontSize: 10,
    color: COLORS.goldPrimary,
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  statValue: {
    fontFamily: FONTS.bold,
    fontSize: 24,
    color: COLORS.goldDarkText,
  },
  detailsCard: {
    backgroundColor: COLORS.white,
    borderWidth: 1.5,
    borderColor: COLORS.goldBorder,
    borderRadius: 8,
    marginBottom: 20,
    overflow: 'hidden',
  },
  detailsHeader: {
    backgroundColor: COLORS.goldLightBg,
    borderBottomWidth: 1.5,
    borderColor: COLORS.goldBorder,
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  detailsHeaderTitle: {
    fontFamily: FONTS.bold,
    fontSize: 15,
    color: COLORS.goldDarkText,
  },
  detailsBody: {
    paddingHorizontal: 16,
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  detailIcon: {
    marginRight: 16,
  },
  detailLabel: {
    fontFamily: FONTS.bold,
    fontSize: 10,
    color: COLORS.textLight,
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  detailValue: {
    fontFamily: FONTS.bold,
    fontSize: 14,
    color: COLORS.textPrimary,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  completedBadgeCount: {
    backgroundColor: COLORS.goldPrimary,
    borderRadius: 10,
    width: 20,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
  },
  badgeCountText: {
    fontFamily: FONTS.bold,
    fontSize: 10,
    color: COLORS.white,
  },
  shipmentsBody: {
    padding: 16,
    alignItems: 'center',
  },
  emptyContainer: {
    alignItems: 'center',
    paddingVertical: 16,
  },
  emptyIconBox: {
    width: 48,
    height: 48,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.goldBorder,
    backgroundColor: COLORS.goldLightBg,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  emptyText: {
    fontFamily: FONTS.bold,
    fontSize: 14,
    color: COLORS.textSecondary,
    textAlign: 'center',
  },
  completedShipmentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    paddingVertical: 8,
  },
  completedShipmentText: {
    fontFamily: FONTS.regular,
    fontSize: 13,
    color: COLORS.textPrimary,
    marginLeft: 12,
  },
  logoutButton: {
    flexDirection: 'row',
    backgroundColor: COLORS.goldPrimary,
    height: 48,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  logoutIcon: {
    marginRight: 8,
  },
  logoutText: {
    fontFamily: FONTS.bold,
    fontSize: 16,
    color: COLORS.white,
  },
});

export  default styles