import { StyleSheet } from 'react-native';
import {
  COLORS,
  FONT_SIZE,
  FONTS,
  RADIUS,
  SPACING,
} from '../../../../../constants';

const styles = StyleSheet.create({
  card: {
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.grey200,
    borderRadius: RADIUS.lg,
    marginBottom: SPACING.md,
    overflow: 'hidden',
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: COLORS.goldLightBg || '#FFFBEB',
    borderBottomWidth: 1,
    borderColor: COLORS.goldBorder || '#FDE68A',
    paddingVertical: 14,
    paddingHorizontal: 16,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  headerIconContainer: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: COLORS.white,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: COLORS.goldBorder || '#FDE68A',
  },
  cardHeaderTitle: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.md,
    color: COLORS.goldDarkText || '#92400E',
  },
  cardHeaderSubtitle: {
    fontFamily: FONTS.medium,
    fontSize: FONT_SIZE.mini,
    color: COLORS.textSecondary,
    marginTop: 1,
  },
  manifestBadge: {
    backgroundColor: COLORS.white,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: RADIUS.xs,
    borderWidth: 1,
    borderColor: COLORS.goldBorder || '#FDE68A',
  },
  manifestBadgeText: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.mini,
    color: COLORS.primary,
    letterSpacing: 0.8,
  },
  cardBody: {
    padding: 16,
  },
  horseCard: {
    borderWidth: 1,
    borderColor: COLORS.grey200,
    borderRadius: RADIUS.md,
    overflow: 'hidden',
    marginBottom: 16,
    backgroundColor: COLORS.white,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  imageContainer: {
    width: '100%',
    height: 190,
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
  },
  horseImage: {
    width: '100%',
    height: '100%',
  },
  imageBottomOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  horseNameBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(15, 23, 42, 0.85)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: RADIUS.xs,
    maxWidth: '65%',
  },
  horseNameBadgeText: {
    color: COLORS.white,
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.xs,
  },
  zoomPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: COLORS.primary,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: RADIUS.xs,
  },
  zoomPillText: {
    color: COLORS.white,
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.mini,
  },
  detailsContent: {
    padding: 14,
  },
  nameHeaderBlock: {
    marginBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.grey100 || '#F1F5F9',
    paddingBottom: 8,
  },
  registeredNameTitle: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.md,
    color: COLORS.textPrimary,
  },
  barnNameSub: {
    fontFamily: FONTS.medium,
    fontSize: FONT_SIZE.xs,
    color: COLORS.textSecondary,
    marginTop: 2,
  },
  specsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  specBox: {
    width: '48%',
    backgroundColor: COLORS.grey50 || '#F8FAFC',
    borderWidth: 1,
    borderColor: COLORS.grey200,
    borderRadius: RADIUS.xs,
    padding: 10,
  },
  specHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginBottom: 4,
  },
  specLabel: {
    fontFamily: FONTS.bold,
    fontSize: 10,
    color: COLORS.textSecondary,
    letterSpacing: 0.6,
  },
  specValue: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.textPrimary,
  },
  notesBox: {
    backgroundColor: COLORS.goldLightBg || '#FFFBEB',
    borderWidth: 1,
    borderColor: COLORS.goldBorder || '#FDE68A',
    borderLeftWidth: 4,
    borderLeftColor: COLORS.primary,
    borderRadius: RADIUS.sm,
    padding: 14,
    marginBottom: 16,
  },
  notesHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 6,
  },
  notesBoxLabel: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.primary,
    letterSpacing: 0.5,
  },
  notesBoxText: {
    fontFamily: FONTS.regular,
    fontSize: FONT_SIZE.xs,
    color: COLORS.goldDarkText || '#92400E',
    lineHeight: 18,
  },
  mapBtn: {
    borderRadius: RADIUS.md,
  },
});

export default styles;
