import { StyleSheet } from "react-native";
import { COLORS, FONT_SIZE, FONTS, RADIUS, SPACING } from "../../../constants";

const styles = StyleSheet.create({
  cardContainer: {
    backgroundColor: COLORS.white,
    marginHorizontal: SPACING.md,
    marginBottom: SPACING.md,
    borderRadius: RADIUS.xl,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: SPACING.md,
    shadowColor: COLORS.textPrimary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingBottom: SPACING.sm,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.divider,
  },
  avatarWrapper: {
    position: 'relative',
    marginRight: SPACING.sm,
  },
  avatarImg: {
    width: 52,
    height: 52,
    borderRadius: 26,
    borderWidth: 2,
    borderColor: COLORS.beigeBorder,
  },
  avatarPlaceholder: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: COLORS.beigeBg,
    borderWidth: 1.5,
    borderColor: COLORS.beigeBorder,
    justifyContent: 'center',
    alignItems: 'center',
  },
  statusDot: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 13,
    height: 13,
    borderRadius: 6.5,
    borderWidth: 2,
    borderColor: COLORS.white,
  },
  headerInfoCol: {
    flex: 1,
  },
  nameRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  driverName: {
    fontSize: FONT_SIZE.md + 1,
    fontFamily: FONTS.bold,
    color: COLORS.textPrimary,
    flex: 1,
    marginRight: SPACING.xs,
  },
  statusBadge: {
    paddingHorizontal: SPACING.xs + 2,
    paddingVertical: 3,
    borderRadius: RADIUS.round,
  },
  badgeActive: {
    backgroundColor: COLORS.greenLightBg,
    borderWidth: 1,
    borderColor: COLORS.greenBorder,
  },
  badgeInactive: {
    backgroundColor: COLORS.divider,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  statusBadgeText: {
    fontSize: FONT_SIZE.xs - 1,
    fontFamily: FONTS.bold,
  },
  textActive: {
    color: COLORS.greenPrimary,
  },
  textInactive: {
    color: COLORS.textSecondary,
  },
  licensePill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.beigeBg,
    alignSelf: 'flex-start',
    paddingHorizontal: SPACING.xs + 2,
    paddingVertical: 2,
    borderRadius: RADIUS.xs,
    marginTop: 4,
    borderWidth: 1,
    borderColor: COLORS.beigeBorder,
  },
  licenseText: {
    fontSize: FONT_SIZE.xs - 1,
    fontFamily: FONTS.medium,
    color: COLORS.saddleBrown,
    marginLeft: 4,
  },
  noLicenseText: {
    fontSize: FONT_SIZE.xs - 1,
    fontFamily: FONTS.regular,
    color: COLORS.textLight,
    marginTop: 2,
  },
  infoGrid: {
    paddingVertical: SPACING.sm,
    gap: 8,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconCircle: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: COLORS.beigeBg,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: SPACING.xs,
    borderWidth: 1,
    borderColor: COLORS.beigeBorder,
  },
  infoText: {
    fontSize: FONT_SIZE.xs + 1,
    fontFamily: FONTS.regular,
    color: COLORS.grey700,
    flex: 1,
  },
  notesBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: COLORS.background,
    padding: SPACING.xs + 2,
    borderRadius: RADIUS.xs,
    borderWidth: 1,
    borderColor: COLORS.divider,
    marginTop: 2,
    gap: 6,
  },
  notesText: {
    fontSize: FONT_SIZE.xs,
    fontFamily: FONTS.regular,
    color: COLORS.textSecondary,
    flex: 1,
  },
  actionFooter: {
    flexDirection: 'row',
    gap: SPACING.xs,
    paddingTop: SPACING.xs,
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 9,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    gap: 6,
  },
  btnActivate: {
    backgroundColor: COLORS.greenLightBg,
    borderColor: COLORS.greenBorder,
  },
  btnDeactivate: {
    backgroundColor: COLORS.brandBrownLightBg,
    borderColor: COLORS.goldBorder,
  },
  btnEdit: {
    backgroundColor: COLORS.background,
    borderColor: COLORS.border,
  },
  btnDelete: {
    backgroundColor: COLORS.redLightBg,
    borderColor: COLORS.redBorder,
  },
  actionBtnText: {
    fontSize: FONT_SIZE.xs,
    fontFamily: FONTS.semiBold,
  },
});
export default styles