import { StyleSheet } from "react-native";
import { COLORS, FONT_SIZE, FONTS } from "../../../../constants";

const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: COLORS.white,
    },
    flexOne: {
        flex: 1,
    },
    navBar: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.border,
    },
    backButton: {
        marginRight: 16,
    },
    navTitleContainer: {
        flex: 1,
    },
    navTitle: {
        fontFamily: FONTS.bold,
        fontSize: 18,
        color: COLORS.textPrimary,
    },
    navSubtitle: {
        fontFamily: FONTS.medium,
        fontSize: FONT_SIZE.sm,
        color: COLORS.textLight,
        marginTop: 2,
    },
    container: {
        flex: 1,
        backgroundColor: COLORS.background,
    },
    scrollContent: {
        paddingHorizontal: 16,
        paddingTop: 24,
        paddingBottom: 40,
    },
    stepperContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 12,
        marginBottom: 24,
    },
    stepWrapper: {
        alignItems: 'center',
        width: 68,
    },
    stepCircle: {
        width: 36,
        height: 36,
        borderRadius: 18,
        borderWidth: 2,
        borderColor: COLORS.grey200,
        backgroundColor: COLORS.white,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 6,
    },
    stepCircleActive: {
        borderColor: COLORS.primary,
    },
    stepCircleCompleted: {
        borderColor: COLORS.primary,
        backgroundColor: COLORS.primary,
    },
    stepNumber: {
        fontFamily: FONTS.bold,
        fontSize: 14,
        color: COLORS.textLight,
    },
    stepNumberActive: {
        color: COLORS.primary,
    },
    stepLabel: {
        fontFamily: FONTS.medium,
        fontSize: FONT_SIZE.sm,

        color: COLORS.textLight,
        textAlign: 'center',
    },
    stepLabelActive: {
        color: COLORS.primary,
        fontFamily: FONTS.bold,
    },
    stepLine: {
        flex: 1,
        height: 2,
        backgroundColor: COLORS.grey200,
        marginHorizontal: -12,
        marginTop: -16,
        zIndex: -1,
    },
    stepLineCompleted: {
        backgroundColor: COLORS.primary,
    },
    shipmentCard: {
        backgroundColor: COLORS.white,
        borderWidth: 1.5,
        borderColor: COLORS.goldBorder,
        borderRadius: 8,
        padding: 16,
        marginBottom: 24,
    },
    shipmentHeaderLabel: {
        fontFamily: FONTS.bold,
        fontSize: FONT_SIZE.xs,
        color: COLORS.textLight,
        letterSpacing: 0.5,
        marginBottom: 12,
    },
    shipmentTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 16,
    },
    shipmentTitle: {
        fontFamily: FONTS.bold,
        fontSize: 18,
        color: COLORS.textPrimary,
    },
    passengerCountBadge: {
        borderWidth: 1,
        borderColor: COLORS.goldBorder,
        backgroundColor: COLORS.goldLightBg,
        borderRadius: 16,
        paddingVertical: 4,
        paddingHorizontal: 12,
    },
    badgeText: {
        fontFamily: FONTS.bold,
        fontSize: FONT_SIZE.sm,

        color: COLORS.primary,
    },
    stopBox: {
        backgroundColor: COLORS.goldLightBg,
        borderWidth: 1,
        borderColor: COLORS.goldBorder,
        borderRadius: 8,
        paddingVertical: 12,
        paddingHorizontal: 14,
        marginBottom: 12,
    },
    stopHeaderLabel: {
        fontFamily: FONTS.bold,
        fontSize: 9,
        color: COLORS.textLight,
        letterSpacing: 0.5,
        marginBottom: 2,
    },
    stopName: {
        fontFamily: FONTS.bold,
        fontSize: 13,
        color: COLORS.textPrimary,
    },
    metaRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.border,
    },
    metaIcon: {
        marginRight: 12,
    },
    metaLabel: {
        fontFamily: FONTS.bold,
        fontSize: 9,
        color: COLORS.textLight,
        letterSpacing: 0.5,
        marginBottom: 1,
    },
    metaValue: {
        fontFamily: FONTS.bold,
        fontSize: 13,
        color: COLORS.textPrimary,
    },
    centerSection: {
        alignItems: 'center',
        paddingHorizontal: 8,
        marginBottom: 20,
    },
    middleIconBox: {
        width: 64,
        height: 64,
        borderRadius: 12,
        borderWidth: 1.5,
        borderColor: COLORS.goldBorder,
        backgroundColor: COLORS.goldLightBg,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 16,
    },
    mainActionHeading: {
        fontFamily: FONTS.bold,
        fontSize: 22,
        color: COLORS.textPrimary,
        marginBottom: 8,
        textAlign: 'center',
    },
    mainActionDescription: {
        fontFamily: FONTS.regular,
        fontSize: 13,
        color: COLORS.textSecondary,
        textAlign: 'center',
        lineHeight: 18,
        paddingHorizontal: 16,
    },
    successBanner: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: COLORS.greenLightBg,
        borderWidth: 1,
        borderColor: COLORS.greenBorder,
        borderRadius: 20,
        paddingVertical: 8,
        paddingHorizontal: 16,
        marginTop: 16,
        width: '100%',
    },
    successBannerText: {
        fontFamily: FONTS.bold,
        fontSize: FONT_SIZE.sm,
        color: COLORS.greenActive,
        marginLeft: 8,
    },
    otpGridContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        marginTop: 24,
        paddingHorizontal: 8,
    },
    otpInputBox: {
        width: 44,
        height: 52,
        borderWidth: 1.5,
        borderColor: COLORS.border,
        borderRadius: 8,
        backgroundColor: COLORS.white,
        fontFamily: FONTS.bold,
        fontSize: 20,
        color: COLORS.textPrimary,
    },
    otpLabelDigits: {
        fontFamily: FONTS.medium,
        fontSize: FONT_SIZE.sm,
        color: COLORS.textLight,
        marginTop: 10,
        marginBottom: 20,
    },
    resendTextLink: {
        fontFamily: FONTS.bold,
        fontSize: 14,
        color: COLORS.primary,
    },
    footerContainer: {
        backgroundColor: COLORS.white,
        borderTopWidth: 1,
        borderTopColor: COLORS.border,
        padding: 16,
    },
    goldActionButton: {
        flexDirection: 'row',
        backgroundColor: COLORS.primary,
        height: 52,
        borderRadius: 26, // Rounded pill design
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: COLORS.black,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 6,
        elevation: 4,
    },
    actionBtnIcon: {
        marginRight: 8,
    },
    actionBtnText: {
        fontFamily: FONTS.bold,
        fontSize: 16,
        color: COLORS.white,
    },
});

export default styles