import { StyleSheet } from "react-native";
import { COLORS, FONT_SIZE, FONTS, RADIUS, SPACING, SIZES } from "../../../../constants";

const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: COLORS.white,
    },
    flexOne: {
        flex: 1,
    },
    navBar: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: SPACING.lg,
        paddingVertical: SPACING.md,
        borderBottomWidth: SIZES.borderWidthThin,
        borderBottomColor: COLORS.border,
    },
    backButton: {
        marginRight: SPACING.lg,
    },
    navTitleContainer: {
        flex: 1,
    },
    navTitle: {
        fontFamily: FONTS.bold,
        fontSize: FONT_SIZE.xl,
        color: COLORS.textPrimary,
    },
    navSubtitle: {
        fontFamily: FONTS.medium,
        fontSize: FONT_SIZE.sm,
        color: COLORS.textLight,
        marginTop: SPACING.xxs,
    },
    container: {
        flex: 1,
        backgroundColor: COLORS.background,
    },
    scrollContent: {
        paddingHorizontal: SPACING.lg,
        paddingTop: SPACING.xxl,
        paddingBottom: SPACING.giant,
    },
    stepperContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: SPACING.md,
        marginBottom: SPACING.xxl,
    },
    stepWrapper: {
        alignItems: 'center',
        width: 68,
    },
    stepCircle: {
        width: 36,
        height: 36,
        borderRadius: 18,
        borderWidth: SIZES.borderWidthThick,
        borderColor: COLORS.grey200,
        backgroundColor: COLORS.white,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: SPACING.xs2,
    },
    stepCircleActive: {
        borderColor: COLORS.primary,
    },
    stepCircleCompleted: {
        borderColor: COLORS.primary,
        backgroundColor: COLORS.primary,
    },
    stepNumber: {
        fontFamily: FONTS.bold,
        fontSize: FONT_SIZE.md,
        color: COLORS.textLight,
    },
    stepNumberActive: {
        color: COLORS.primary,
    },
    stepLabel: {
        fontFamily: FONTS.medium,
        fontSize: FONT_SIZE.sm,

        color: COLORS.textLight,
        textAlign: 'center',
    },
    stepLabelActive: {
        color: COLORS.primary,
        fontFamily: FONTS.bold,
    },
    stepLine: {
        flex: 1,
        height: 2,
        backgroundColor: COLORS.grey200,
        marginHorizontal: -12,
        marginTop: -16,
        zIndex: -1,
    },
    stepLineCompleted: {
        backgroundColor: COLORS.primary,
    },
    shipmentCard: {
        backgroundColor: COLORS.white,
        borderWidth: 1.5,
        borderColor: COLORS.goldBorder,
        borderRadius: RADIUS.sm,
        padding: SPACING.lg,
        marginBottom: SPACING.xxl,
    },
    shipmentHeaderLabel: {
        fontFamily: FONTS.bold,
        fontSize: FONT_SIZE.xs,
        color: COLORS.textLight,
        letterSpacing: 0.5,
        marginBottom: SPACING.md,
    },
    shipmentTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: SPACING.lg,
    },
    shipmentTitle: {
        fontFamily: FONTS.bold,
        fontSize: FONT_SIZE.xl,
        color: COLORS.textPrimary,
    },
    passengerCountBadge: {
        borderWidth: SIZES.borderWidthThin,
        borderColor: COLORS.goldBorder,
        backgroundColor: COLORS.goldLightBg,
        borderRadius: RADIUS.lg,
        paddingVertical: SPACING.xs,
        paddingHorizontal: SPACING.md,
    },
    badgeText: {
        fontFamily: FONTS.bold,
        fontSize: FONT_SIZE.sm,

        color: COLORS.primary,
    },
    stopBox: {
        backgroundColor: COLORS.goldLightBg,
        borderWidth: SIZES.borderWidthThin,
        borderColor: COLORS.goldBorder,
        borderRadius: RADIUS.sm,
        paddingVertical: SPACING.md,
        paddingHorizontal: SPACING.md2,
        marginBottom: SPACING.md,
    },
    stopHeaderLabel: {
        fontFamily: FONTS.bold,
        fontSize: FONT_SIZE.mini,
        color: COLORS.textLight,
        letterSpacing: 0.5,
        marginBottom: SPACING.xxs,
    },
    stopName: {
        fontFamily: FONTS.bold,
        fontSize: FONT_SIZE.md,
        color: COLORS.textPrimary,
    },
    metaRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: SPACING.md,
        borderBottomWidth: SIZES.borderWidthThin,
        borderBottomColor: COLORS.border,
    },
    metaIcon: {
        marginRight: SPACING.md,
    },
    metaLabel: {
        fontFamily: FONTS.bold,
        fontSize: FONT_SIZE.mini,
        color: COLORS.textLight,
        letterSpacing: 0.5,
        marginBottom: 1,
    },
    metaValue: {
        fontFamily: FONTS.bold,
        fontSize: FONT_SIZE.md,
        color: COLORS.textPrimary,
    },
    centerSection: {
        alignItems: 'center',
        paddingHorizontal: SPACING.sm,
        marginBottom: SPACING.xl,
    },
    middleIconBox: {
        width: 64,
        height: 64,
        borderRadius: RADIUS.md,
        borderWidth: 1.5,
        borderColor: COLORS.goldBorder,
        backgroundColor: COLORS.goldLightBg,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: SPACING.lg,
    },
    mainActionHeading: {
        fontFamily: FONTS.bold,
        fontSize: FONT_SIZE.title,
        color: COLORS.textPrimary,
        marginBottom: SPACING.sm,
        textAlign: 'center',
    },
    mainActionDescription: {
        fontFamily: FONTS.regular,
        fontSize: FONT_SIZE.md,
        color: COLORS.textSecondary,
        textAlign: 'center',
        lineHeight: 18,
        paddingHorizontal: SPACING.lg,
    },
    successBanner: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: COLORS.greenLightBg,
        borderWidth: SIZES.borderWidthThin,
        borderColor: COLORS.greenBorder,
        borderRadius: RADIUS.xl,
        paddingVertical: SPACING.sm,
        paddingHorizontal: SPACING.lg,
        marginTop: SPACING.lg,
        width: '100%',
    },
    successBannerText: {
        fontFamily: FONTS.bold,
        fontSize: FONT_SIZE.sm,
        color: COLORS.greenActive,
        marginLeft: SPACING.sm,
    },
    otpGridContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        marginTop: SPACING.xxl,
        paddingHorizontal: SPACING.sm,
    },
    otpInputBox: {
        width: 44,
        height: 52,
        borderWidth: 1.5,
        borderColor: COLORS.border,
        borderRadius: RADIUS.sm,
        backgroundColor: COLORS.white,
        justifyContent: 'center',
        alignItems: 'center',
    },
    activeOtpInputBox: {
        borderColor: COLORS.primary,
        borderWidth: 2,
    },
    otpPinCodeText: {
        fontFamily: FONTS.bold,
        fontSize: FONT_SIZE.xxl,
        color: COLORS.textPrimary,
        textAlign: 'center',
    },
    otpLabelDigits: {
        fontFamily: FONTS.medium,
        fontSize: FONT_SIZE.sm,
        color: COLORS.textLight,
        marginTop: SPACING.sm2,
        marginBottom: SPACING.xl,
    },
    resendTextLink: {
        fontFamily: FONTS.bold,
        fontSize: FONT_SIZE.md,
        color: COLORS.primary,
    },
    footerContainer: {
        backgroundColor: COLORS.white,
        borderTopWidth: SIZES.borderWidthThin,
        borderTopColor: COLORS.border,
        padding: SPACING.lg,
    },
    goldActionButton: {
        flexDirection: 'row',
        backgroundColor: COLORS.primary,
        height: 52,
        borderRadius: 26, // Rounded pill design
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: COLORS.black,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 6,
        elevation: 4,
    },
    actionBtnIcon: {
        marginRight: SPACING.sm,
    },
    actionBtnText: {
        fontFamily: FONTS.bold,
        fontSize: FONT_SIZE.lg,
        color: COLORS.white,
    },
});

export default styles;