import { StyleSheet } from 'react-native';
import { COLORS, FONTS, SPACING, RADIUS, FONT_SIZE } from '../../../../../constants';

const styles = StyleSheet.create({
  tabSection: {
    gap: SPACING.sm,
  },
  sectionHeaderTitle: {
    fontSize: FONT_SIZE.lg,
    fontFamily: FONTS.bold,
    color: COLORS.textPrimary || '#1E293B',
  },
  sectionHeaderSub: {
    fontSize: FONT_SIZE.xs,
    fontFamily: FONTS.regular,
    color: COLORS.textSecondary || '#64748B',
    marginTop: 2,
    marginBottom: SPACING.xs,
  },
  redAlertBanner: {
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FCA5A5',
    borderRadius: RADIUS.xs || 6,
    padding: SPACING.md - 2,
    marginBottom: SPACING.xs,
  },
  redAlertText: {
    fontSize: FONT_SIZE.xs,
    fontFamily: FONTS.medium,
    color: '#DC2626',
  },
  payoutMainCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: RADIUS.md || 12,
    borderWidth: 1,
    borderColor: '#FDE68A',
    overflow: 'hidden',
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 6,
    elevation: 2,
  },
  payoutAccountCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.md,
    padding: SPACING.md,
  },
  goldHorseIconBox: {
    width: 44,
    height: 44,
    borderRadius: RADIUS.xs || 8,
    backgroundColor: '#FAF6EE',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E6D7BD',
  },
  payoutTextCol: {
    flex: 1,
  },
  payoutTitle: {
    fontSize: FONT_SIZE.sm + 1,
    fontFamily: FONTS.bold,
    color: COLORS.textPrimary || '#1E293B',
  },
  payoutSub: {
    fontSize: FONT_SIZE.xs,
    fontFamily: FONTS.regular,
    color: COLORS.textSecondary || '#64748B',
    marginTop: 2,
  },
  notConnectedBadge: {
    borderWidth: 1,
    borderColor: '#FCD34D',
    backgroundColor: '#FEFCE8',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
  },
  notConnectedBadgeText: {
    fontSize: 11,
    fontFamily: FONTS.bold,
    color: '#92400E',
  },
  connectedBadge: {
    borderWidth: 1,
    borderColor: '#A7F3D0',
    backgroundColor: '#ECFDF5',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
  },
  connectedBadgeText: {
    fontSize: 11,
    fontFamily: FONTS.bold,
    color: '#047857',
  },
  cardDivider: {
    height: 1,
    backgroundColor: '#F3F4F6',
  },

  // Stepper Bar
  stepperContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.md,
  },
  stepperNode: {
    alignItems: 'center',
  },
  stepperCircleActive: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#A06333',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.white,
  },
  stepperDotActive: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#A06333',
  },
  stepperLabelActive: {
    fontSize: 11,
    fontFamily: FONTS.bold,
    color: '#8C5226',
    marginTop: 4,
  },
  stepperCircleInactive: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#CBD5E1',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.white,
  },
  stepperLabelInactive: {
    fontSize: 11,
    fontFamily: FONTS.regular,
    color: '#94A3B8',
    marginTop: 4,
  },
  stepperLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#E2E8F0',
    marginHorizontal: 4,
    marginBottom: 16,
  },

  payoutActionSection: {
    padding: SPACING.md,
  },
  connectDescription: {
    fontSize: FONT_SIZE.xs + 1,
    fontFamily: FONTS.regular,
    color: COLORS.textSecondary || '#64748B',
    lineHeight: 18,
  },
  setupPayoutBtn: {
    backgroundColor: '#A06333',
    borderRadius: RADIUS.md || 20,
    paddingHorizontal: SPACING.lg,
    paddingVertical: 11,
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 6,
    marginTop: SPACING.md,
    shadowColor: '#A06333',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 3,
  },
  setupPayoutBtnText: {
    color: COLORS.white,
    fontSize: FONT_SIZE.xs + 1,
    fontFamily: FONTS.bold,
  },

  verifiedCard: {
    backgroundColor: '#FAF6EE',
    padding: SPACING.md,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: SPACING.md,
  },
  checkSquare: {
    width: 32,
    height: 32,
    borderRadius: RADIUS.xs || 6,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: '#E6D7BD',
    justifyContent: 'center',
    alignItems: 'center',
  },
  verifiedTextCol: {
    flex: 1,
  },
  verifiedTitle: {
    fontSize: FONT_SIZE.sm,
    fontFamily: FONTS.bold,
    color: COLORS.textPrimary || '#1E293B',
    marginBottom: 4,
  },
  verifiedSub: {
    fontSize: FONT_SIZE.xs,
    fontFamily: FONTS.regular,
    color: COLORS.textSecondary || '#64748B',
    lineHeight: 18,
  },
  encryptionFooterBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#FAF6EE',
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderTopWidth: 1,
    borderTopColor: '#FDE68A',
  },
  encryptionFooterText: {
    fontSize: 10,
    fontFamily: FONTS.bold,
    color: '#A06333',
    letterSpacing: 0.6,
    flex: 1,
  },
});

export default styles;
