import { StyleSheet } from 'react-native';
import { COLORS, FONTS, SPACING, RADIUS, FONT_SIZE } from '../../../../../constants';

const styles = StyleSheet.create({
  tabSection: {
    gap: SPACING.md,
  },
  sectionHeaderTitle: {
    fontSize: FONT_SIZE.lg,
    fontFamily: FONTS.bold,
    color: COLORS.textPrimary || '#1E293B',
  },
  sectionHeaderSub: {
    fontSize: FONT_SIZE.xs,
    fontFamily: FONTS.regular,
    color: COLORS.textSecondary || '#64748B',
    marginTop: 2,
    marginBottom: SPACING.sm,
  },
  subCardContainer: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.md || 12,
    borderWidth: 1,
    borderColor: COLORS.goldBorder || '#E6D7BD',
    padding: SPACING.md,
    marginBottom: SPACING.md,
  },
  subCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
  },
  goldSquareIconBox: {
    width: 40,
    height: 40,
    borderRadius: RADIUS.xs || 8,
    backgroundColor: COLORS.goldLightBg || '#FAF6EE',
    justifyContent: 'center',
    alignItems: 'center',
  },
  subHeaderTextCol: {
    flex: 1,
  },
  subHeaderTitle: {
    fontSize: FONT_SIZE.md,
    fontFamily: FONTS.bold,
    color: COLORS.textPrimary || '#1E293B',
  },
  subHeaderSub: {
    fontSize: FONT_SIZE.xs,
    fontFamily: FONTS.regular,
    color: COLORS.textSecondary || '#64748B',
    marginTop: 2,
  },
  subActiveBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#ECFDF5',
    borderWidth: 1,
    borderColor: '#A7F3D0',
    paddingHorizontal: SPACING.xs + 2,
    paddingVertical: 3,
    borderRadius: RADIUS.round || 20,
  },
  subActiveBadgeText: {
    fontSize: FONT_SIZE.xs - 1,
    fontFamily: FONTS.bold,
    color: '#059669',
  },
  cardDivider: {
    height: 1,
    backgroundColor: COLORS.divider || '#E2E8F0',
    marginVertical: SPACING.md,
  },
  statusPillsRow: {
    flexDirection: 'row',
    gap: SPACING.xs,
    marginVertical: SPACING.xs,
  },
  greenOutlinePill: {
    paddingHorizontal: SPACING.md,
    paddingVertical: 5,
    borderRadius: RADIUS.round || 20,
    borderWidth: 1,
    borderColor: '#059669',
    backgroundColor: '#ECFDF5',
  },
  greenOutlinePillText: {
    fontSize: FONT_SIZE.xs,
    fontFamily: FONTS.bold,
    color: '#059669',
  },
  blueOutlinePill: {
    paddingHorizontal: SPACING.md,
    paddingVertical: 5,
    borderRadius: RADIUS.round || 20,
    borderWidth: 1,
    borderColor: '#2563EB',
    backgroundColor: '#EFF6FF',
  },
  blueOutlinePillText: {
    fontSize: FONT_SIZE.xs,
    fontFamily: FONTS.bold,
    color: '#2563EB',
  },
  goldOutlinePill: {
    paddingHorizontal: SPACING.md,
    paddingVertical: 5,
    borderRadius: RADIUS.round || 20,
    borderWidth: 1,
    borderColor: COLORS.goldBorder || '#E6D7BD',
    backgroundColor: COLORS.goldLightBg || '#FAF6EE',
  },
  goldOutlinePillText: {
    fontSize: FONT_SIZE.xs,
    fontFamily: FONTS.bold,
    color: COLORS.primary || '#A06333',
  },
  planDetailsBox: {
    backgroundColor: COLORS.goldLightBg || '#FAF6EE',
    borderRadius: RADIUS.sm || 10,
    borderWidth: 1,
    borderColor: COLORS.goldBorder || '#E6D7BD',
    padding: SPACING.md,
    marginVertical: SPACING.sm,
    gap: SPACING.xs,
  },
  planDetailsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  planLabel: {
    fontSize: FONT_SIZE.xs - 2,
    fontFamily: FONTS.bold,
    color: COLORS.primary || '#A06333',
    letterSpacing: 0.6,
  },
  planRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginTop: 4,
  },
  planName: {
    fontSize: FONT_SIZE.md + 1,
    fontFamily: FONTS.bold,
    color: COLORS.textPrimary || '#1E293B',
  },
  planPeriodText: {
    fontSize: FONT_SIZE.xs,
    fontFamily: FONTS.regular,
    color: COLORS.textSecondary || '#64748B',
    marginTop: 2,
  },
  planPrice: {
    fontSize: FONT_SIZE.md,
    fontFamily: FONTS.bold,
    color: COLORS.textPrimary || '#1E293B',
  },
  planBillingFrequency: {
    fontSize: FONT_SIZE.xs - 1,
    fontFamily: FONTS.regular,
    color: COLORS.textSecondary || '#64748B',
    marginTop: 1,
  },
  subActiveBannerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: SPACING.xs,
    marginTop: SPACING.xs,
  },
  subActiveBanner: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
    backgroundColor: '#ECFDF5',
    borderWidth: 1,
    borderColor: '#A7F3D0',
    borderRadius: RADIUS.xs || 8,
    padding: SPACING.sm,
  },
  subActiveBannerText: {
    fontSize: FONT_SIZE.xs,
    fontFamily: FONTS.bold,
    color: '#059669',
  },
  cancelSubTriggerBtn: {
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FCA5A5',
    paddingHorizontal: SPACING.sm + 2,
    paddingVertical: SPACING.sm,
    borderRadius: RADIUS.xs || 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelSubTriggerBtnText: {
    fontSize: FONT_SIZE.xs,
    fontFamily: FONTS.bold,
    color: '#DC2626',
  },
  subCancelingBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
    backgroundColor: '#FFFBEB',
    borderWidth: 1,
    borderColor: '#FDE68A',
    borderRadius: RADIUS.xs || 8,
    padding: SPACING.sm,
    marginTop: SPACING.xs,
  },
  subCancelingBannerText: {
    fontSize: FONT_SIZE.xs,
    fontFamily: FONTS.bold,
    color: '#D97706',
    flex: 1,
  },
  billingFilterRow: {
    flexDirection: 'row',
    gap: SPACING.xs,
    marginVertical: SPACING.sm,
    flexWrap: 'wrap',
  },
  billingFilterPill: {
    paddingHorizontal: SPACING.sm + 2,
    paddingVertical: 6,
    borderRadius: RADIUS.round || 20,
    backgroundColor: COLORS.grey100 || '#F1F5F9',
    borderWidth: 1,
    borderColor: COLORS.divider || '#CBD5E1',
  },
  billingFilterPillActive: {
    backgroundColor: COLORS.goldLightBg || '#FAF6EE',
    borderColor: COLORS.goldBorder || '#E6D7BD',
  },
  billingFilterText: {
    fontSize: FONT_SIZE.xs,
    fontFamily: FONTS.medium,
    color: COLORS.textSecondary || '#64748B',
  },
  billingFilterTextActive: {
    color: COLORS.primary || '#A06333',
    fontFamily: FONTS.bold,
  },

  historyListContainer: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.md || 12,
    borderWidth: 1,
    borderColor: COLORS.goldBorder || '#E6D7BD',
    overflow: 'hidden',
    marginTop: SPACING.xs,
  },
  historyCardItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    padding: SPACING.md,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    gap: SPACING.sm,
  },
  itemIconBox: {
    width: 36,
    height: 36,
    borderRadius: RADIUS.xs || 8,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 2,
  },
  itemContentCol: {
    flex: 1,
    gap: 4,
  },
  itemTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: SPACING.xs,
  },
  itemTitleText: {
    fontSize: FONT_SIZE.xs + 1,
    fontFamily: FONTS.bold,
    color: COLORS.textPrimary || '#1E293B',
    flex: 1,
  },
  itemAmountText: {
    fontSize: FONT_SIZE.xs + 1,
    fontFamily: FONTS.bold,
    color: COLORS.textPrimary || '#1E293B',
  },
  itemBottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  itemDateText: {
    fontSize: FONT_SIZE.xs - 1,
    fontFamily: FONTS.regular,
    color: COLORS.textSecondary || '#64748B',
  },
  itemCardText: {
    fontSize: FONT_SIZE.xs - 1,
    fontFamily: FONTS.medium,
    color: COLORS.textSecondary || '#64748B',
  },
  itemBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  statusBadgePill: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: RADIUS.xs || 4,
  },
  statusBadgeSuccess: {
    backgroundColor: '#ECFDF5',
    borderWidth: 1,
    borderColor: '#A7F3D0',
  },
  statusBadgeTrial: {
    backgroundColor: '#EFF6FF',
    borderWidth: 1,
    borderColor: '#BFDBFE',
  },
  statusBadgeText: {
    fontSize: 10,
    fontFamily: FONTS.bold,
  },
  statusBadgeTextSuccess: {
    color: '#059669',
  },
  statusBadgeTextTrial: {
    color: '#2563EB',
  },
  viewPdfBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: COLORS.goldLightBg || '#FAF6EE',
    borderWidth: 1,
    borderColor: COLORS.goldBorder || '#E6D7BD',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: RADIUS.xs || 4,
  },
  viewPdfBtnText: {
    fontSize: 11,
    fontFamily: FONTS.bold,
    color: COLORS.primary || '#A06333',
  },

  emptySubCard: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.lg || 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: SPACING.xxl || 32,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: SPACING.sm,
  },
  crownCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#FEF3C7',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: SPACING.md,
  },
  emptySubTitle: {
    fontSize: FONT_SIZE.lg || 18,
    fontFamily: FONTS.bold,
    color: '#0F172A',
    marginBottom: 4,
  },
  emptySubSub: {
    fontSize: FONT_SIZE.xs + 1,
    fontFamily: FONTS.regular,
    color: '#64748B',
    marginBottom: SPACING.md,
  },
  subscribeNowBtn: {
    backgroundColor: '#A06333',
    paddingHorizontal: SPACING.lg,
    paddingVertical: 10,
    borderRadius: RADIUS.md || 8,
  },
  subscribeNowBtnText: {
    color: COLORS.white,
    fontSize: FONT_SIZE.sm,
    fontFamily: FONTS.bold,
  },
});

export default styles;
