import { StyleSheet } from 'react-native';
import {
  COLORS,
  FONT_SIZE,
  FONTS,
  RADIUS,
  SIZES,
  SPACING,
} from '../../../../../constants';
import { moderateScale } from 'react-native-size-matters';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.background,
  },

  scrollContent: {
    paddingHorizontal: SPACING.lg,
    paddingTop: SPACING.sm,
    paddingBottom: moderateScale(90),
  },

  /* Hero */
  heroCard: {
    backgroundColor: COLORS.surface,
    borderRadius: RADIUS.xl,
    padding: SPACING.lg,
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  heroTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  shipmentIcon: {
    width: SIZES.avatarLg,
    height: SIZES.avatarLg,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.goldCreamBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroInfo: {
    flex: 1,
    marginLeft: SPACING.md,
  },
  heroLabel: {
    fontFamily: FONTS.semiBold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.textLight,
    letterSpacing: 0.7,
  },
  heroCode: {
    marginTop: SPACING.xs,
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.lg,
    color: COLORS.textPrimary,
  },
  statusBadge: {
    minHeight: moderateScale(30),
    paddingHorizontal: SPACING.sm2,
    borderRadius: RADIUS.pill,
    flexDirection: 'row',
    alignItems: 'center',
  },
  statusDot: {
    width: moderateScale(7),
    height: moderateScale(7),
    borderRadius: RADIUS.circle,
    marginRight: SPACING.xs,
  },
  statusText: {
    fontFamily: FONTS.semiBold,
    fontSize: FONT_SIZE.xs,
  },
  heroDivider: {
    height: 1,
    backgroundColor: COLORS.divider,
    marginVertical: SPACING.md,
  },
  heroBottomRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  heroMeta: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  heroMetaText: {
    marginLeft: SPACING.xs,
    fontFamily: FONTS.medium,
    fontSize: FONT_SIZE.xs,
    color: COLORS.textSecondary,
  },

  /* Section */
  sectionHeader: {
    marginTop: SPACING.xxl,
    marginBottom: SPACING.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.lg,
    color: COLORS.textPrimary,
  },
  sectionSubtitle: {
    marginTop: SPACING.xs,
    fontFamily: FONTS.regular,
    fontSize: FONT_SIZE.xs,
    color: COLORS.textSecondary,
  },
  routeIcon: {
    width: SIZES.iconActionBtn,
    height: SIZES.iconActionBtn,
    borderRadius: RADIUS.sm,
    backgroundColor: COLORS.goldCreamBg,
    alignItems: 'center',
    justifyContent: 'center',
  },

  /* Route Card */
  routeCard: {
    backgroundColor: COLORS.surface,
    borderRadius: RADIUS.xl,
    padding: SPACING.lg,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  locationRow: {
    flexDirection: 'row',
  },
  timelineContainer: {
    width: moderateScale(24),
    alignItems: 'center',
  },
  locationDot: {
    width: moderateScale(12),
    height: moderateScale(12),
    borderRadius: RADIUS.circle,
    borderWidth: 3,
    borderColor: COLORS.surface,
  },
  timelineLine: {
    width: 2,
    flex: 1,
    minHeight: moderateScale(65),
    marginVertical: SPACING.xs,
    backgroundColor: COLORS.border,
  },
  locationContent: {
    flex: 1,
    marginLeft: SPACING.md,
    paddingBottom: SPACING.lg,
  },
  locationHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  locationType: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.textSecondary,
    letterSpacing: 0.7,
  },
  datePill: {
    backgroundColor: COLORS.greenLightBg,
    paddingHorizontal: SPACING.sm,
    paddingVertical: SPACING.xs,
    borderRadius: RADIUS.pill,
    flexDirection: 'row',
    alignItems: 'center',
  },
  datePillText: {
    marginLeft: SPACING.xs,
    fontFamily: FONTS.semiBold,
    fontSize: FONT_SIZE.xxs,
    color: COLORS.greenPrimary,
  },
  locationText: {
    marginTop: SPACING.sm,
    fontFamily: FONTS.medium,
    fontSize: FONT_SIZE.sm,
    lineHeight: moderateScale(20),
    color: COLORS.textPrimary,
  },
  timeRow: {
    marginTop: SPACING.sm,
    flexDirection: 'row',
    alignItems: 'center',
  },
  timeText: {
    marginLeft: SPACING.xs,
    fontFamily: FONTS.regular,
    fontSize: FONT_SIZE.xs,
    color: COLORS.textLight,
  },

  /* Interactive Map Card & Calculation */
  mapCardContainer: {
    marginTop: SPACING.lg,
    backgroundColor: COLORS.surface,
    borderRadius: RADIUS.xl,
    padding: SPACING.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  mapHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: SPACING.sm,
  },
  mapHeaderInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  mapHeaderTitle: {
    marginLeft: SPACING.xs,
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.md,
    color: COLORS.textPrimary,
  },
  recenterBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: SPACING.sm,
    paddingVertical: SPACING.xs,
    borderRadius: RADIUS.pill,
    backgroundColor: COLORS.goldCreamBg,
    gap: 4,
  },
  recenterText: {
    fontFamily: FONTS.semiBold,
    fontSize: FONT_SIZE.xxs,
    color: COLORS.primary,
  },
  mapWrapper: {
    height: moderateScale(210),
    borderRadius: RADIUS.md,
    overflow: 'hidden',
    position: 'relative',
  },
  mapView: {
    width: '100%',
    height: '100%',
  },
  markerBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: COLORS.white,
    elevation: 3,
  },
  mapStatsCard: {
    position: 'absolute',
    bottom: SPACING.xs,
    left: SPACING.xs,
    right: SPACING.xs,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: RADIUS.md,
    padding: SPACING.xs,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 4,
  },
  mapStatItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
  },
  mapStatContent: {
    justifyContent: 'center',
  },
  mapStatLabel: {
    fontSize: 9,
    fontFamily: FONTS.semiBold,
    color: COLORS.textLight,
    letterSpacing: 0.5,
  },
  mapStatVal: {
    fontSize: FONT_SIZE.xs,
    fontFamily: FONTS.bold,
    color: COLORS.textPrimary,
  },
  mapStatDivider: {
    width: 1,
    height: 24,
    backgroundColor: COLORS.divider,
  },

  /* Summary */
  summaryCard: {
    marginTop: SPACING.lg,
    backgroundColor: COLORS.surface,
    borderRadius: RADIUS.xl,
    padding: SPACING.lg,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  summaryHeader: {
    marginBottom: SPACING.lg,
  },
  summaryTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  smallIconContainer: {
    width: SIZES.iconActionBtn,
    height: SIZES.iconActionBtn,
    borderRadius: RADIUS.sm,
    backgroundColor: COLORS.goldCreamBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  summaryTitle: {
    marginLeft: SPACING.sm,
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.md,
    color: COLORS.textPrimary,
  },
  summaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    rowGap: SPACING.lg,
  },
  summaryItem: {
    width: '50%',
  },
  summaryLabel: {
    fontFamily: FONTS.semiBold,
    fontSize: FONT_SIZE.xxs,
    letterSpacing: 0.6,
    color: COLORS.textLight,
  },
  summaryValue: {
    marginTop: SPACING.xs,
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.lg,
    color: COLORS.textPrimary,
  },
  summaryValueSmall: {
    marginTop: SPACING.xs,
    fontFamily: FONTS.semiBold,
    fontSize: FONT_SIZE.sm,
    color: COLORS.textPrimary,
  },

  /* Horse */
  horseCard: {
    backgroundColor: COLORS.surface,
    borderRadius: RADIUS.xl,
    padding: SPACING.lg,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  horseHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  horseAvatar: {
    width: SIZES.avatarXl,
    height: SIZES.avatarXl,
    borderRadius: RADIUS.lg,
    backgroundColor: COLORS.goldCreamBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  horseNameContainer: {
    flex: 1,
    marginLeft: SPACING.md,
  },
  horseName: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.lg,
    color: COLORS.textPrimary,
  },
  horseBarnName: {
    marginTop: SPACING.xs,
    fontFamily: FONTS.regular,
    fontSize: FONT_SIZE.xs,
    color: COLORS.textSecondary,
  },
  horseAgeBadge: {
    width: moderateScale(48),
    height: moderateScale(48),
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.goldCreamBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  horseAge: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.lg,
    color: COLORS.primaryDark,
  },
  horseAgeLabel: {
    marginTop: -2,
    fontFamily: FONTS.medium,
    fontSize: FONT_SIZE.xxs,
    color: COLORS.goldBrownText,
  },
  horseDivider: {
    height: 1,
    backgroundColor: COLORS.divider,
    marginVertical: SPACING.lg,
  },
  horseDetailsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    rowGap: SPACING.lg,
  },
  horseDetailItem: {
    width: '50%',
    flexDirection: 'row',
    alignItems: 'center',
    paddingRight: SPACING.sm,
  },
  horseDetailIcon: {
    width: moderateScale(30),
    height: moderateScale(30),
    borderRadius: RADIUS.sm,
    backgroundColor: COLORS.goldCreamBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  horseDetailContent: {
    flex: 1,
    marginLeft: SPACING.sm,
  },
  horseDetailLabel: {
    fontFamily: FONTS.regular,
    fontSize: FONT_SIZE.xxs,
    color: COLORS.textLight,
  },
  horseDetailValue: {
    marginTop: 2,
    fontFamily: FONTS.semiBold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.textPrimary,
  },
  infoBox: {
    marginTop: SPACING.lg,
    padding: SPACING.md,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.goldLightBg,
    borderWidth: 1,
    borderColor: COLORS.goldBorder,
  },
  infoBoxHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  infoBoxTitle: {
    marginLeft: SPACING.xs,
    fontFamily: FONTS.semiBold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.goldDarkText,
  },
  infoBoxText: {
    marginTop: SPACING.sm,
    fontFamily: FONTS.regular,
    fontSize: FONT_SIZE.xs,
    lineHeight: moderateScale(18),
    color: COLORS.textPrimary,
  },
  notesBox: {
    marginTop: SPACING.sm,
    padding: SPACING.md,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.grey50,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  notesTitle: {
    marginLeft: SPACING.xs,
    fontFamily: FONTS.semiBold,
    fontSize: FONT_SIZE.xs,
    color: COLORS.textSecondary,
  },
  notesText: {
    marginTop: SPACING.sm,
    fontFamily: FONTS.regular,
    fontSize: FONT_SIZE.xs,
    lineHeight: moderateScale(18),
    color: COLORS.textSecondary,
  },

  /* Customer */
  customerCard: {
    backgroundColor: COLORS.surface,
    borderRadius: RADIUS.lg,
    padding: SPACING.md,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  customerAvatar: {
    width: SIZES.avatarMd44,
    height: SIZES.avatarMd44,
    borderRadius: RADIUS.circle,
    backgroundColor: COLORS.goldCreamBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  customerInfo: {
    flex: 1,
    marginLeft: SPACING.md,
  },
  customerName: {
    fontFamily: FONTS.semiBold,
    fontSize: FONT_SIZE.md,
    color: COLORS.textPrimary,
  },
  customerMeta: {
    marginTop: SPACING.xs,
    flexDirection: 'row',
    alignItems: 'center',
  },
  customerEmail: {
    marginLeft: SPACING.xs,
    fontFamily: FONTS.regular,
    fontSize: FONT_SIZE.xs,
    color: COLORS.textSecondary,
  },

  /* Message */
  messageCard: {
    marginTop: SPACING.lg,
    padding: SPACING.md,
    borderRadius: RADIUS.lg,
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    flexDirection: 'row',
  },
  messageIcon: {
    width: SIZES.iconActionBtn,
    height: SIZES.iconActionBtn,
    borderRadius: RADIUS.sm,
    backgroundColor: COLORS.goldCreamBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  messageContent: {
    flex: 1,
    marginLeft: SPACING.md,
  },
  messageTitle: {
    fontFamily: FONTS.semiBold,
    fontSize: FONT_SIZE.sm,
    color: COLORS.textPrimary,
  },
  messageText: {
    marginTop: SPACING.xs,
    fontFamily: FONTS.regular,
    fontSize: FONT_SIZE.xs,
    lineHeight: moderateScale(18),
    color: COLORS.textSecondary,
  },

  /* Bottom Sticky Action Bar */
  bottomSpacing: {
    height: moderateScale(80),
  },
  stickyBottomBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: COLORS.surface,
    borderTopWidth: 1,
    borderTopColor: COLORS.divider,
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.md,
    elevation: 8,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
  },
  askQuestionBtn: {
    flex: 1,
    height: 48,
    borderRadius: RADIUS.md,
    borderWidth: 1.5,
    borderColor: COLORS.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: SPACING.xs,
    backgroundColor: COLORS.white,
  },
  askQuestionBtnText: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.sm,
    color: COLORS.primary,
  },
  submitOfferBtn: {
    flex: 1.2,
    height: 48,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: SPACING.xs,
  },
  submitOfferBtnText: {
    fontFamily: FONTS.bold,
    fontSize: FONT_SIZE.sm,
    color: COLORS.white,
  },
});

export default styles;
